@API_HostAddress = http://localhost:5094

GET {{API_HostAddress}}/api/products/
Accept: application/json

###

GET {{API_HostAddress}}/api/products/1
Content-Type: application/json

###

POST {{API_HostAddress}}/api/products/
Content-Type: application/json

{
  "name": "Lamp",
  "categoryId": "Home/Furniture",
  "description": "A cozy lamp for reading",
  "inStock": true,
  "quantity": 40
}

###

PUT {{API_HostAddress}}/api/products/14
Content-Type: application/json

{
  "id": 14,
  "name": "test",
  "categoryId": "test",
  "description": "update",
  "inStock": true,
  "quantity": 69
}

###

DELETE {{API_HostAddress}}/api/products/6
Content-Type: application/json