@API_HostAddress = http://localhost:5094

GET {{API_HostAddress}}/api/products/
Accept: application/json

###

GET {{API_HostAddress}}/api/products/2
Content-Type: application/json

###

POST {{API_HostAddress}}/api/products/
Content-Type: application/json

{
  "name": "test",
  "categoryId": "test",
  "description": "test"
}

###

PUT {{API_HostAddress}}/api/products/2
Content-Type: application/json

{
  "id": 1,
  "name": "test",
  "categoryId": "test",
  "description": "update"
}

###

DELETE {{API_HostAddress}}/api/products/6
Content-Type: application/json